
name: validate-dois
on:
  push:
    paths:
      - 'dois/**'
      - 'scripts/validate_dois.py'
      - '.github/workflows/validate-dois.yml'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests
      - run: python scripts/validate_dois.py
